/*
 Navicat Premium Data Transfer

 Source Server         : postgre-mac
 Source Server Type    : PostgreSQL
 Source Server Version : 100015
 Source Host           : localhost:5432
 Source Catalog        : libraryCatalog
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 100015
 File Encoding         : 65001

 Date: 23/03/2021 00:50:45
*/


-- ----------------------------
-- Table structure for books
-- ----------------------------
DROP TABLE IF EXISTS "public"."books";
CREATE TABLE "public"."books" (
  "bookText" varchar COLLATE "pg_catalog"."default",
  "likes" int4,
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "bookTitle" varchar(100) COLLATE "pg_catalog"."default"
)
;
ALTER TABLE "public"."books" OWNER TO "postgres";

-- ----------------------------
-- Primary Key structure for table books
-- ----------------------------
ALTER TABLE "public"."books" ADD CONSTRAINT "books_pkey" PRIMARY KEY ("id");
