/*
 Navicat Premium Data Transfer

 Source Server         : postgres-miguel
 Source Server Type    : PostgreSQL
 Source Server Version : 130003
 Source Host           : localhost:5432
 Source Catalog        : libraryCatalog
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 130003
 File Encoding         : 65001

 Date: 24/07/2021 15:29:35
*/


-- ----------------------------
-- Table structure for books
-- ----------------------------
DROP TABLE IF EXISTS "public"."books";
CREATE TABLE "public"."books" (
  "bookText" varchar COLLATE "pg_catalog"."default",
  "likes" int4,
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "bookTitle" varchar(100) COLLATE "pg_catalog"."default"
)
;
ALTER TABLE "public"."books" OWNER TO "postgres";

-- ----------------------------
-- Records of books
-- ----------------------------
BEGIN;
INSERT INTO "public"."books" VALUES ('se desarrolla en la sierra del peru', 15, 2, 'paco yunque');
INSERT INTO "public"."books" VALUES ('se desarrolla en la sierra del peru', 15, 3, 'paco yunque');
INSERT INTO "public"."books" VALUES ('La historia de la vida', 5, 4, 'la pequeña gran historia');
INSERT INTO "public"."books" VALUES ('se desarrolla en la sierra del peru', 15, 5, 'paco yunque');
INSERT INTO "public"."books" VALUES ('Eren es un titan', 29, 6, 'ataque a los titanes');
COMMIT;

-- ----------------------------
-- Primary Key structure for table books
-- ----------------------------
ALTER TABLE "public"."books" ADD CONSTRAINT "books_pkey" PRIMARY KEY ("id");
