/*
 Navicat Premium Data Transfer

 Source Server         : postgres-miguel
 Source Server Type    : PostgreSQL
 Source Server Version : 130003
 Source Host           : localhost:5432
 Source Catalog        : libraryCatalog
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 130003
 File Encoding         : 65001

 Date: 23/07/2021 21:24:02
*/


-- ----------------------------
-- Table structure for todos
-- ----------------------------
DROP TABLE IF EXISTS "public"."todos";
CREATE TABLE "public"."todos" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "title" varchar(20) COLLATE "pg_catalog"."default",
  "todo_description" varchar(100) COLLATE "pg_catalog"."default"
)
;
ALTER TABLE "public"."todos" OWNER TO "postgres";

-- ----------------------------
-- Records of todos
-- ----------------------------
BEGIN;
INSERT INTO "public"."todos" VALUES (1, 'desayuno', 'se prepara la primera comida del dia');
INSERT INTO "public"."todos" VALUES (2, 'almuerzo', 'se prepara la sopa y el segundo');
INSERT INTO "public"."todos" VALUES (3, 'jugar sc', 'vamos a ingresar a battle.net');
INSERT INTO "public"."todos" VALUES (4, 'jugar sc', 'vamos a ingresar a battle.net');
COMMIT;

-- ----------------------------
-- Primary Key structure for table todos
-- ----------------------------
ALTER TABLE "public"."todos" ADD CONSTRAINT "todos_pkey" PRIMARY KEY ("id");
